# Generated by Django 5.1.3 on 2024-12-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Poetry and Literature', 'Poetry and Literature'), ('Technical and Professional', 'Technical and Professional'), ('Academic and Education', 'Academic and Education')], max_length=50),
        ),
    ]
