# Generated by Django 5.1.3 on 2024-12-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.CharField(help_text='Format: YYYY-MM', max_length=7),
        ),
    ]
